RF:
  n_estimators: [20, 50, 200, 300, 400]
  max_depth: [2, 10, 20, 30]
  min_samples_leaf: [1, 15, 20, 30]
  min_samples_split: [2, 5, 8, 12, 15]
  max_features: ["auto"]

EBM:
  learning_rate: [0.005, 0.01, 0.05]
  max_leaves: [1, 2, 3, 4]
  max_bins: [512, 1024]
  inner_bags: [10, 25, 50]
  outer_bags: [25]
  interactions: [0]
  max_rounds: [3000, 5000, 10000]
  min_samples_leaf: [2, 4]

XGB:
  max_depth: [2]
  subsample: [1.0]
  eta: [.03, .1, .3, .5]
  n_estimators: [50, 100, 200, 300]
  num_parallel_tree: [1]
