EBM:
  inner_bags: [25]
  interactions: [0]
  learning_rate: [0.05]
  max_bins: [1024]
  max_leaves: [2]
  max_rounds: [3000]
  min_samples_leaf: [4]
  outer_bags: [25]
RF:
  max_depth: [30]
  max_features: [auto]
  min_samples_leaf: [15]
  min_samples_split: [5]
  n_estimators: [400]
XGB:
  max_depth: [2]
  n_estimators: [100]
  num_parallel_tree: [1]
  subsample: [1.0]
